# Generated by .github/workflows/update-united-bar.yml. Edits are overwritten.
cask "united-bar" do
  version "0.1.0-tip-68dff43"
  sha256 "9cd5919f2ff69ed4dca09cc4d94fbb731c1bcba3a6eea74c1c50b27f754ee19f"

  # Rolling: `tip` is a moving tag republished on every push to main,
  # so the URL never changes. The version above exists only to make
  # `brew upgrade` notice that a new build landed.
  url "https://github.com/tale/united-bar/releases/download/tip/united-bar-tip-aarch64-macos.zip",
      verified: "github.com/tale/united-bar/"
  name "United Bar"
  desc "Menu bar app that tracks the United flight you are on"
  homepage "https://github.com/tale/united-bar"

  livecheck do
    skip "Rolling release; the upstream release workflow updates this cask"
  end

  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "UnitedBar.app"

  uninstall quit: "me.tale.UnitedBar"

  zap trash: [
    "~/Library/Caches/me.tale.UnitedBar",
    "~/Library/HTTPStorages/me.tale.UnitedBar",
    "~/Library/Preferences/me.tale.UnitedBar.plist",
  ]

  caveats <<~EOS
    United Bar only reports while you are connected to United's
    in-flight wifi. On the ground the panel shows an error.
  EOS
end
