# Generated by .github/workflows/update-prtui.yml. Edits are overwritten.
class Prtui < Formula
  desc "Terminal UI for reviewing GitHub pull requests"
  homepage "https://github.com/tale/prtui"
  version "0.1.0"
  license "MIT"

  depends_on "gh"

  # The repo is public now, so HEAD needs no key: plain HTTPS works
  # and a source build is the only thing that wants a toolchain.
  head do
    url "https://github.com/tale/prtui.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/tale/prtui/releases/download/v0.1.0/prtui-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "7a5e8f257d04f0a42eefbb6f787b189514ee4a531b57df8216582e3e70277c4f"
    end
    on_intel do
      url "https://github.com/tale/prtui/releases/download/v0.1.0/prtui-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "779c4c2f476a556787e7d68151c219d0239fef5f58a345e2bdaee1d46f78595f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tale/prtui/releases/download/v0.1.0/prtui-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f05ea1074a3d4a172f4cded0c01c1b87647712cdd6f7ed922d81aab16a936478"
    end
    on_intel do
      url "https://github.com/tale/prtui/releases/download/v0.1.0/prtui-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a2f15e03bb81bbe66a26dd19db8302eb58de1997223548cc816eff4bd26b2f7f"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "prtui"
    end
  end

  test do
    assert_match "prtui #{version}", shell_output("#{bin}/prtui --version")
  end
end
