# Generated by .github/workflows/update-prtui.yml. Edits are overwritten.
class Prtui < Formula
  desc "Terminal UI for reviewing GitHub pull requests"
  homepage "https://github.com/tale/prtui"
  version "0.2.0"
  license "MIT"

  depends_on "gh"

  # The repo is public now, so HEAD needs no key: plain HTTPS works
  # and a source build is the only thing that wants a toolchain.
  head do
    url "https://github.com/tale/prtui.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/tale/prtui/releases/download/v0.2.0/prtui-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "b8e4d828d15b4d268163810934f1c22f36257e7a4ffe413555ed7691af2478dd"
    end
    on_intel do
      url "https://github.com/tale/prtui/releases/download/v0.2.0/prtui-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "51c0bdf7316b98aa95bd66296e5dc91b1233cb63ad1af8ab7d75d4e59f9639c9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tale/prtui/releases/download/v0.2.0/prtui-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "5fafb757b7e79c783d87cb9dfcabdf4cb5291d66f5596c5a90b8d786c768790d"
    end
    on_intel do
      url "https://github.com/tale/prtui/releases/download/v0.2.0/prtui-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f8010816602d96ef929cae680f2a12bfc6aa2b1358f532670c83e14b2a2e780b"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "prtui"
    end
  end

  test do
    assert_match "prtui #{version}", shell_output("#{bin}/prtui --version")
  end
end
