# Generated by .github/workflows/update-prtui.yml. Edits are overwritten.
class Prtui < Formula
  desc "Terminal UI for reviewing GitHub and GitLab changes"
  homepage "https://github.com/tale/prtui"
  version "0.4.0"
  license "MIT"

  # The repo is public now, so HEAD needs no key: plain HTTPS works
  # and a source build is the only thing that wants a toolchain.
  head do
    url "https://github.com/tale/prtui.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/tale/prtui/releases/download/v0.4.0/prtui-v0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "2b4b92163eb420073b79096bf2ba81da16de5ebfa78404ca854ea47946a93024"
    end
    on_intel do
      url "https://github.com/tale/prtui/releases/download/v0.4.0/prtui-v0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "682dff285e0da041cd3d400b313e88b5e4c5a9f2ded759b7b122fb7506d71a33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tale/prtui/releases/download/v0.4.0/prtui-v0.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1f64fa8301d6fe6310b98eaec9b045e2f9b193c3f0ab2bdaf68ddb2372337cb2"
    end
    on_intel do
      url "https://github.com/tale/prtui/releases/download/v0.4.0/prtui-v0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2d8607558390b9d67676e8e8991a834463cb82fae773a63abd28f3380e389f32"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: "crates/prtui")
    else
      bin.install "prtui"
    end
  end

  def caveats
    <<~EOS
      For GitHub reviews, install gh and run gh auth login.
      For GitLab reviews, install glab and run glab auth login --hostname HOST.
      Local diffs only require Git.
    EOS
  end

  test do
    assert_match(/\Aprtui \d+\.\d+\.\d+/, shell_output("#{bin}/prtui --version"))
  end
end
